Repository FACG6/Gaza-Freelancing-Community, pull requests merged in 2019-03, with the labels that each got.

#43 integrating travis
  .travis.yml
Labels: for merge

#42 File structure
  .gitignore
  package.json
  public/css/home.css
  public/js/helpers/dom.js
Labels: for merge

#45 Database Configuration
  package-lock.json
  package.json
  src/database/config/db_build.js
  src/database/config/db_build.sql
  src/database/config/db_connection.js
Labels: need review

#47 Install Eslint
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  src/app.js
  src/controllers/index.js
  src/index.js
Labels: Eslint, for merge

#51 Data Configuration
  package-lock.json
  package.json
  src/database/config/db_connection.js
Labels: need review

#49 Edit server
  package.json
  src/app.js
  src/controllers/index.js
  src/index.js
Labels: need review

#46 Layouts
  src/views/layouts/error.hbs
  src/views/layouts/login_signup.hbs
  src/views/layouts/main.hbs
  src/views/layouts/profile.hbs
Labels: Back-End, need review

#60 Collect data
  public/js/helpers/collectData.js
Labels: need review

#56 Setup views
  package-lock.json
  package.json
  src/app.js
  src/database/config/db_connection.js
Labels: need review, view

#57 Partials
  src/app.js
  src/views/layouts/error.hbs
  src/views/layouts/login_signup.hbs
  src/views/layouts/main.hbs
  src/views/layouts/profile.hbs
  src/views/partials/footer.hbs
  src/views/partials/head.hbs
  src/views/partials/header.hbs
  src/views/partials/script.hbs
  src/views/partials/sidebar.hbs
  src/views/signup.hbs
Labels: Back-End, waiting review

#61 Signup view
  src/views/signup.hbs
Labels: in progress

#75 Schema validation
  package-lock.json
  package.json
  src/helpers/validation-schemes.js
Labels: waiting review

#64 Hashing password
  src/helpers/hashPass.js
Labels: Back-End, helpers, waiting review

#77 Travis
  .travis.yml
  package-lock.json
  test/test.js
Labels: deployment, waiting review

#67 Read me
  README.md
Labels: read me, waiting review

#76 makeTitle helper
  src/app.js
  src/views/helpers/index.js
  src/views/helpers/makeTitle.js
Labels: Back-End, helpers, waiting review

#85 Npm modules
  package-lock.json
  package.json
  src/controllers/index.js
  src/controllers/login.js
  src/views/layouts/error.hbs
  src/views/layouts/login_signup.hbs
  src/views/layouts/profile.hbs
  src/views/partials/header.hbs
  src/views/partials/script.hbs
  src/views/partials/sidebar.hbs
Labels: waiting review

#58 Signup Render page
  package-lock.json
  src/controllers/index.js
  src/controllers/signup.js
  src/controllers/specialization.js
  src/database/config/db_build.js
  src/database/config/db_build.sql
  src/database/config/db_connection.js
  src/database/queries/getData.js
  src/index.js
  src/views/helpers/index.js
  src/views/layouts/error.hbs
  src/views/layouts/login_signup.hbs
  src/views/layouts/profile.hbs
  src/views/partials/head.hbs
  src/views/partials/header.hbs
  src/views/partials/script.hbs
  src/views/partials/sidebar.hbs
  test/test.js
Labels: waiting review

#62 Adduser query
  package-lock.json
  package.json
  public/css/login.css
  src/database/queries/addData.js
  src/views/layouts/login_signup.hbs
  src/views/login.hbs
  src/views/partials/footer.hbs
  test/test.js
Labels: waiting review

#63 Signup post
  package-lock.json
  public/js/helpers/signup.js
  src/controllers/index.js
  src/controllers/signup.js
  src/database/queries/getData.js
  src/views/helpers/index.js
  test/test.js
Labels: waiting review

#82 Error pages
  public/css/error.css
  src/controllers/error.js
  src/controllers/index.js
  src/views/error.hbs
  src/views/layouts/error.hbs
Labels: waiting review

#81 Logout router
  src/controllers/index.js
  src/controllers/logout.js
  test/test.js
Labels: Back-End, routes, waiting review

#94 Authorization Middleware
  package-lock.json
  src/controllers/index.js
  src/middlewares/authorization.js
Labels: waiting review

#90 Login post
  src/controllers/index.js
  src/controllers/login.js
  src/database/config/db_build.sql
  src/helpers/createtoken.js
  src/helpers/validation-schemes.js
  src/middlewares/authentication.js
  test/test.js
Labels: Back-End, waiting review

#89 Login dom
  public/js/login.js
  src/views/login.hbs
Labels: waiting review

#95 Login css
  public/css/login.css
  src/controllers/home.js
  src/controllers/index.js
  src/database/queries/getData.js
  src/views/home.hbs
  src/views/layouts/login_signup.hbs
  src/views/layouts/profile.hbs
  src/views/partials/head.hbs
  src/views/partials/header.hbs
Labels: waiting review

#87 Sign up dom
  .eslintrc.json
  public/js/helpers/signup.js
  public/js/signup.js
  src/controllers/index.js
  src/controllers/specialization.js
  src/views/partials/head.hbs
  src/views/signup.hbs
Labels: Front-End, waiting review

#86 Get proposal
  public/css/proposal.css
  src/controllers/index.js
  src/controllers/proposal.js
  src/database/config/db_build.sql
  src/database/queries/addData.js
  src/database/queries/getData.js
  src/views/proposal.hbs
  test/test.js
Labels: Back-End, routes, waiting review

#91 Query of proposal
  src/database/queries/getData.js
  test/test.js
Labels: waiting review

#92 Render home
  src/controllers/index.js
  src/database/config/db_build.sql
Labels: done

#97 Search Query
  src/controllers/index.js
  src/controllers/search.js
  src/database/queries/getData.js
  test/test.js
  test/testingQuery.js
Labels: waiting review

#96 Settings get
  src/controllers/index.js
  src/controllers/settings.js
  src/database/queries/getData.js
  src/views/settings.hbs
Labels: routes, waiting review

#109 Setting and profile
  public/css/profile.css
  public/css/settings.css
  src/views/partials/sidebar.hbs
  src/views/settings.hbs
Labels: waiting review

#100 Home front
  public/css/home.css
  public/js/home.js
  src/controllers/home.js
  src/controllers/index.js
  src/controllers/middlewares/jwtVerification.js
  src/views/home.hbs
  src/views/layouts/main.hbs
  src/views/partials/header.hbs
Labels: Front-End, waiting review
